### PR TITLE
Added tests if method searchable and unsearchable exist

### PR DESCRIPTION
**Pull request by stevenvandemoortele**
Got an error when using solspace freeform with scout installed and sync enabled.
The freeform submission element doesn't have the method searchable.

### CODE REVIEW

**Comment by riasvdv** [comment]
We register the behavior on the base Element class of Craft though, can you comment the exact error you're getting in your logs?

**Comment by riasvdv** [comment]
Can you test if it works when you use `$element->ensureBehaviors();` before it calls `$element->searchable()`?

**Comment by stevenvandemoortele** [comment]
I've tried adding `$element->ensureBehaviours();` before it calls `$element->searchable()` like you suggested but I get the same error.

The error I'm getting is the following:
```2019-09-19 16:16:20 [-][1][po4n196ihrbcbmei6mcipa2c59][error][Solspace\Freeform\Library\Exceptions\FieldExceptions\FieldException] Solspace\Freeform\Library\Exceptions\FieldExceptions\FieldException: Field "searchable" not found in /Users/stevenvandemoortele/Sites/site.test/vendor/solspace/craft-freeform/src/Elements/Submission.php:734
Stack trace:
#0 /Users/stevenvandemoortele/Sites/site.test/vendor/solspace/craft-freeform/src/Elements/Submission.php(556): Solspace\Freeform\Elements\Submission->getFieldByIdentifier('searchable')
#1 /Users/stevenvandemoortele/Sites/site.test/vendor/rias/craft-scout/src/Scout.php(156): Solspace\Freeform\Elements\Submission->__call('searchable', Array)
#2 [internal function]: rias\scout\Scout->rias\scout\{closure}(Object(craft\events\ElementEvent))```

**Comment by riasvdv** [comment]
And the exception message? Seems like Solspace is throwing an error in its `_call()` method too soon

**Comment by stevenvandemoortele** [comment]
```2019-09-19 16:16:20 [-][1][po4n196ihrbcbmei6mcipa2c59][error][Solspace\Freeform\Library\Exceptions\FieldExceptions\FieldException] Solspace\Freeform\Library\Exceptions\FieldExceptions\FieldException: Field "searchable" not found in /Users/stevenvandemoortele/Sites/site.test/vendor/solspace/craft-freeform/src/Elements/Submission.php:734```

**Comment by riasvdv** [comment]
Ah yes, seems like they're throwing an exception here https://github.com/solspace/craft3-freeform/blob/v3/src/Elements/Submission.php#L556 instead of returning false to let it go through to any behaviors. I've let them know and I'll keep this open until it's resolved on their end

**Comment by riasvdv** [comment]
This seems to be fixed in a newer version of Freeform, so I'm closing this

**Pull request closed without merging**
