### PR TITLE
Don't include indices in Settings::toArray() by default

### LINKED ISSUE #152: Error with ProjectConfig after settings changed
Hey @riasvdv 

We had Scout working fine but after unticking 'Sync' in the CMS settings, we now get the following error below. Have you seen this before?

Only way to get back in the CMS is to remove the Scout line from phpMyAdmin. Then, I remove it from the plugins list but when installing again, I get the same issue. I'm using the set-up file as per the docs that was working initially with the correct channels. 

If you can point me in the right direction, that would be great. 

Craft CMS 3.4.11, PHP 7.3

PHP Notice – yii\base\ErrorException Undefined offset: 1
vendor/craftcms/cms/src/helpers/ProjectConfig.php line 275

Screenshot 2020-03-30 at 17 44 34

### PR DESCRIPTION
**Pull request by brandonkelly**
Fixes #152

### CODE REVIEW

**Comment by riasvdv** [comment]
Thanks!

**Comment by martinhellwagner** [comment]
@brandonkelly 
@riasvdv 

Strangely, updating to Scout 2.3.1 (which contains the fix mentioned above) doesn't fix the problem for us. We're running Craft 3.4.19.1. Is there anything we still have to take care of?

**Comment by ryanirelan** [comment]
This also happened to me with Scout 2.3.1 and Craft 3.4.27. It happened after a deployment with one single template file change and nothing else.

**Comment by sidoneill** [comment]
@martinhellwagner the issue likely that you still have the offending nested objects stored in your projectconfig table. Look for and delete the plugins.scout.settings rows and you should be good to go (and no longer sweating every update).

**Pull request merged**
